export const SET_WHEEL_SPIN = "SET_WHEEL_SPIN";
export const PROMO_CODE_MATCH = "PROMO_CODE_MATCH";
export const ON_CHECKOUT = "ON_CHECKOUT";
export const INVALID_PROMO_CODE = "INVALID_PROMO_CODE";
export const VALID_PROMO_CODE = "VALID_PROMO_CODE";
export const PROMO_CODE_CLICK = "PROMO_CODE_CLICK";
